### ISSUE TITLE
Debian 11 Bullseye unable to build gtk3 only: meson setup build dies with error about "install_tag"

### ISSUE THREAD

**Issue by l8gravely** [BestImageViewer/geeqie#1005] opened 2022-07-22 11:35 UTC
### ISSUE TYPE
* Bug Reportt

### GEEQIE VERSION
```

```

```
commit e68b6b1bf98f6d03a88f05326e02c060364f5768
```

### OS / DISTRIBUTION
Debian Bullseye (v11)

### SUMMARY
Debian Bullseye cannot do the build because the default version of meson is too old, at 0.54.x instead of the requested 0.60.0 version. 

### STEPS TO REPRODUCE

I was able to get meson father  to run by applying the following patch

diff --git a/meson.build b/meson.build
index 733107a7..27743449 100644
--- a/meson.build
+++ b/meson.build
@@ -44,7 +44,7 @@ project(
     'cpp',
     version : run_command('./version.sh', check : true).stdout().strip(),
     license : ['GPL-2.0-or-later'],
-    meson_version : '>= 0.60.0',
+    meson_version : '>= 0.54.0',
     default_options : ['warning_level=3', 'buildtype=debugoptimized']
 )
 

But it still bombs on the setup, and ends with the following in the meson setup log:

Called `/usr/bin/pkg-config libwebp --libs` -> 0
-lwebp
None of 'PKG_CONFIG_PATH' are defined in the environment, not changing global flags.
Run-time dependency libwebp found: YES 0.6.1
None of 'CC_LD' are defined in the environment, not changing global flags.
Running compile:
Working directory:  /home/locked/src/geeqie-git/build/meson-private/tmpthu82qtp
Command line:  cc /home/locked/src/geeqie-git/build/meson-private/tmpthu82qtp/testfile.c -o /home/locked/src/geeqie-git/build/meson-private/tmpthu82qtp/output.exe -pipe -D_FILE_OFFSET_BITS=64 -O0 

Code:
 #include <langinfo.h>
#include<stdio.h>
int main (int argc, char ** argv) {
    char *c;
    c =  nl_langinfo(_NL_TIME_FIRST_WEEKDAY);
    return 0;
}
Compiler stdout:
 
Compiler stderr:
 
Checking if "nl_langinfo and _NL_TIME_FIRST_WEEKDAY" links: YES 
Configuring config.h using configuration
plugins/camera-import/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/export-jpeg/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/geocode-parameters/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/image-crop/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/lens/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/random-image/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/rotate/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/symlink/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.
plugins/tethered-photography/meson.build:14: WARNING: Passed invalid keyword argument "install_tag".
WARNING: This will become a hard error in the future.

src/icons/meson.build:65:0: ERROR: custom_target: Only one positional argument is allowed, and it must be a string name

**Comment by l8gravely** [comment] 2022-07-22 12:00
So digging in a bit, it looks like it's an issue in src/iconds/meson.build where is doesn't like the construct:

icons_inline_h = custom_target( output : 'icons_inline.h',
        command : [gdk_pixbuf_csource, '--raw', '--extern', '--build-list', icons_inline_pairs],
        capture : true)

But I haven't a clue how to fix this issue. 

So I just commented out this line in the src/meson.build and then the src/icons/meson.build files because the gdk-pixbuf-csource command returned nothing.  Now the build dies with:

Program glib-genmarshal found: YES (/usr/bin/glib-genmarshal)
Program xxd found: YES (/usr/bin/xxd)
WARNING: Project targeting '>= 0.54.0' but tried to use feature introduced in '0.56.0': meson.project_build_root.

doc/meson.build:14:0: ERROR: Non-existent build file 'doc/html/meson.build'

A full log can be found at /home/locked/src/geeqie-git/build/meson-logs/meson-log.txt

**Comment by gusnan** [comment] 2022-07-22 16:30
I have a diff like this which makes it build on Debian with the Debian stable version of meson:

```
diff --git a/meson.build b/meson.build
index 733107a7..3b0e01bc 100644
--- a/meson.build
+++ b/meson.build
@@ -44,7 +44,7 @@ project(
     'cpp',
     version : run_command('./version.sh', check : true).stdout().strip(),
     license : ['GPL-2.0-or-later'],
-    meson_version : '>= 0.60.0',
+    meson_version : '>= 0.56.0',
     default_options : ['warning_level=3', 'buildtype=debugoptimized']
 )
 
diff --git a/src/icons/meson.build b/src/icons/meson.build
index ba4bc2f9..d6be6720 100644
--- a/src/icons/meson.build
+++ b/src/icons/meson.build
@@ -62,7 +62,7 @@ icons_inline_pairs = [
 'icon_split_pane_sync', files('icon_split_pane_sync.png')
 ]
 
-icons_inline_h = custom_target( output : 'icons_inline.h',
+icons_inline_h = custom_target('icons_inline_h', output : 'icons_inline.h',
         command : [gdk_pixbuf_csource, '--raw', '--extern', '--build-list', icons_inline_pairs],
         capture : true)
 
diff --git a/src/meson.build b/src/meson.build
index b433a33c..671a8c6c 100644
--- a/src/meson.build
+++ b/src/meson.build
@@ -250,7 +250,7 @@ icon_pairs = [
 'icon_tabcomp', files('ui_tabcomp.png'),
 ]
 
-ui_icons_h = custom_target(output : 'ui_icons.h',
+ui_icons_h = custom_target('ui_icons_h', output : 'ui_icons.h',
                 command : [gdk_pixbuf_csource, '--raw', '--extern', '--build-list', icon_pairs],
                 capture : true)
```

but I do of course get a lot of warnings like

`meson.build:314: WARNING: Passed invalid keyword argument "install_tag".`

And if upgrading to meson from backports I instead get these warnings (since I changed the geeqie meson build to target 0.56):

`meson.build:314: WARNING: Project targeting '>= 0.56.0' but tried to use feature introduced in '0.60.0': install_tag arg in install_data.`

It seems to be a bit hard (but I don't claim to be a meson expert, far from it) to support both meson 0.56 and above 0.60 at the same time.

**Comment by eli-schwartz** [comment] 2022-07-24 06:14
I think you just described a bunch of good reasons why the current meson.build specifies you need 0.60.0; fundamentally, this is an issue of the project not *supporting* Debian 11.

The issue title is wrong, and misleading -- there is no error about "install_tag", because instead, there's an error about using too old a version of Meson (one which doesn't support install_tag, actually ;)).

Whether or not the project *should* try to support Debian 11, is a different topic than whether or not it fails to build there. I suggest, at least, retitling the issue.

**Comment by caclark** [comment] 2022-07-25 16:20
Fixed in commit db95a097

**Closed by caclark** 2022-07-25 16:20 UTC

**Comment by l8gravely** [comment] 2022-07-25 19:29
Hi Colin,
Thanks for the patches.  It gets much farther in the build, but bombs
on ffmpegthumnailer issues, which I'll open another ticket about when
I get a chance.

John

**Comment by l8gravely** [comment] 2022-10-11 08:45
>>>>> "Eli" == Eli Schwartz ***@***.***> writes:

Eli> I think you just described a bunch of good reasons why the
Eli> current meson.build specifies you need 0.60.0; fundamentally,
Eli> this is an issue of the project not supporting Debian 11.

Sure, that's mostly what I'm trying to point out here, that the move
to meson needs to target the *lowest* common setup that comes with
whatever version of gtk3 and meson and the other build tools.  

Eli> The issue title is wrong, and misleading -- there is no error
Eli> about "install_tag", because instead, there's an error about
Eli> using too old a version of Meson (one which doesn't support
Eli> install_tag, actually ;)).

I was trying to get the new system working on Debian 11, and since I
don't know meson at all, I tried my best to give a good error report.

Eli> Whether or not the project should try to support Debian 11, is a
Eli> different topic than whether or not it fails to build there. I
Eli> suggest, at least, retitling the issue.

I can retitle it to "cannot compile on Debian 11 with Meson 0.56.0" if
that would be clearer.

**Comment by eli-schwartz** [comment] 2022-10-12 00:25
> I was trying to get the new system working on Debian 11, and since I don't know meson at all, I tried my best to give a good error report.

I guess it sort of seems personally to me, a bit as though this isn't entirely true.

The most important -- indeed, I might argue, the ***only*** -- relevant bit of information, is the fact that you had to "get meson farther to run by applying the following patch".

This ***transforms*** the issue from a bug report to a policy issue. An ***unpatched*** geeqie stated that your build environment is just not supported.

This means that any and all errors you get when you try to do it anyway, are expected as a matter of patched build errors, and will only be fixed by... dropping the minimum meson requirement, and adapting to that in the process.

> I can retitle it to "cannot compile on Debian 11 with Meson 0.56.0" if that would be clearer.

Yes, this would be best in general -- because that's what the real issue that needs to be discussed is, and particular instances of things that fail on Debian 11 with meson 0.56.0, are just minor implementation notes in the grand scheme of "this should compile on older versions of Meson that are available on Debian 11'.

That being said, in the commit that closed this ticket the meson.build version constraints were dropped to support Debian 11 (the "real issue that needs to be discussed") so it seems like that did get resolved, but... as a policy issue, not a bug.

That was dealt with 3 months ago. :) So is there anything else still an issue? Given that geeqie now officially supports 0.53, if there's anything that still fails on Debian 11 then it's likely now a very real bug in the minimum declared requirements.
