### ISSUE TITLE
webp images load as black even with every prerequisite being green during compile

### ISSUE THREAD

**Issue by ProtoBelisarius** [BestImageViewer/geeqie#1227] opened 2024-01-21 11:23 UTC
**Setup:**
 - Distribution: EndeavourOS(Arch) KDE 5
 - Distribution release: latest rolling
 - Geeqie version: git source

**Describe the bug**
Compiling from source prevents the display of webp images.

Also the instructions in the readme seem wrong:
`meson configure build -Dpdf=enabled -Dwebp=disabled`
errors out and shows:
`ERROR: Unknown options: "webp"`
So I cant use this to switch it to `-Dwebp=enabled` because it spits out the same error.

**To reproduce**

Compile via the instructions on github here.

`git clone http://git.geeqie.org/git/geeqie.git`
`meson setup build`
`sudo ninja -C build install`

This works and it shows the following during install:
`webp_pixbuf_loader       : webp files supported:
                               YES
`
It also shows webp in the supported file types in the advanced settings when its installed. 

**Expected behavior**
Display webp images

**I dont really have any idea how to further troubleshoot this issue so I will need further instructions on what additional info I should provide.**

Simply installing version 2.1-4 from the extra repo doesnt really help, as this just crashes/closes immediately after opening and throws this error in the terminal:
`geeqie: error while loading shared libraries: libjxl.so.0.8: cannot open shared object file: No such file or directory`
My system however has libjxl 0.9.1.1 and I dont think I can install 0.8 simulataneously.

**Comment by caclark** [comment] 2024-01-21 12:33
Which version of the webp pixbuf loader is installed?

**Comment by mina86** [comment] 2024-01-21 18:48
Duplicate of https://github.com/BestImageViewer/geeqie/issues/1076?

**Closed** 2024-01-22 16:18 UTC
Labels: bug
