### ISSUE TITLE
copy symlinks as symlinks instead of dereferencing them ( patch included )

### ISSUE THREAD

**Issue by gqpwruser** [BestImageViewer/geeqie#544] opened 2017-11-22 21:12 UTC
### ISSUE TYPE
* Feature Request : copy/move symlinks as symlinks instead of dereferencing them ( patch for copying included )

### GEEQIE VERSION
```
Geeqie 1.3
```

### OS / DISTRIBUTION
Linux

### SUMMARY
When copying thousands of symlinked images to other dirs, symlinks get dereferenced and filesystem gets filled up. Included is a patch to copy symlinked images as symlinks.
Caveats for the person integrating this patch:
  1. Same code might be used to move a symlinked image to another dir
  2. The code doesn't know how to keep relative symlinks relative. "ln" from coreutils >= 8.16 knows how to do this when "ln --relative" is used. It would be useful if someone had gutted ln from coreutils to reuser that code (unless coreutils has this in a lib - then it would be sufficient to link this lib with geeqie )

### STEPS TO REPRODUCE
df -k . ; : Select thousands of symlinked images in geeqie-1.3 and press Ctrl-C to copy them someplace. ; df -k .

### Patch: geeqie-1.3--no-symlink-dereferencing-on-copy.patch.nodebug
```
--- geeqie-1.3/src/ui_fileops.c.20171122214400CET       2016-05-27 11:37:56.000000000 +0200
+++ geeqie-1.3/src/ui_fileops.c 2017-11-22 21:39:34.689237566 +0100
@@ -525,6 +525,57 @@
                goto end;
                }

+
+    /* Do not dereference absolute symlinks, but copy them "as is".
+     * For a relative symlink, we don't know how to properly change it when
+     * copied/moved to another dir to keep pointing it to same target as
+     * a relative symlink, so we turn it into absolute symlink using
+     * realpath() instead. */
+       struct stat st;
+       if (lstat_utf8(sl, &st) && S_ISLNK(st.st_mode))
+               {
+
+               gchar *link_target;
+               link_target = g_malloc(PATH_MAX + 1);
+               readlink(sl, link_target, st.st_size);
+               link_target[st.st_size] = '\0';
+
+       if ( link_target[0] != G_DIR_SEPARATOR ) // if it is a relativy symlink
+                       {
+                       gchar *absolute;
+                       absolute = g_malloc(PATH_MAX + 1);
+            char *lastslash = strrchr(sl, G_DIR_SEPARATOR);
+            int len=lastslash-sl+1;
+            strncpy(absolute, sl, len);
+            strcpy(absolute+len, link_target);
+            strcpy(link_target, absolute);
+                       char *realPath;
+                       realPath = realpath(link_target, absolute);
+                       if (realPath != NULL) // successfully resolved into an absolute path
+                               {
+                               g_free(link_target);
+                               link_target = absolute;
+                               }
+                       else                 // could not get absolute path, got some error instead
+                               {
+                               g_free(absolute);
+                               goto orig_copy;  // so try a "normal" copy
+                               }
+                       }
+
+               if ( stat_utf8(tl, &st) ) unlink(tl); // first try to remove directory entry in destination directory if such entry exists
+
+               gint success = ( symlink(link_target, tl) == 0 );
+               g_free(link_target);
+               if ( success )
+                       {
+                       ret = TRUE;
+                       goto end;
+                       }
+
+               } // if symlink did not succeed, continue on to try a copy procedure
+
+       orig_copy:
        fi = fopen(sl, "rb");
        if (!fi) goto end;

```

**Comment by caclark** [comment] 2017-11-25 17:16
Implemented in commit d5521e38f83 at geeqie.org

Relative symbolic links and the Move operation are still not handled

**Comment by tomaszg7** [comment] 2017-12-19 16:26
I don't know why, but on one of my machines a flag `warn_unused_result` is picked up for `readlink()`. I don't see it defined in `/usr/include/unistd.h` resulting in a failed compliation. I use the same gcc and glibc on all machines, but only one is affected. 

Moreover, looking at the code I notice it allocates too much memory - no need to ask for `PATH_MAX+1`, when `lstat()` already tells us how much we need. Also, it looks like at least one possible code path is missing an additional `g_free()`

For some reason I can't attach patch here. Since it is short, I'll paste it here directly:
```
diff --git a/src/ui_fileops.c b/src/ui_fileops.c
index a479010e..ea8c7c1f 100644
--- a/src/ui_fileops.c
+++ b/src/ui_fileops.c
@@ -555,9 +555,15 @@ gboolean copy_file(const gchar *s, const gchar *t)
        if (lstat_utf8(sl, &st) && S_ISLNK(st.st_mode))
                {
                gchar *link_target;
+               ssize_t i;
 
-               link_target = g_malloc(PATH_MAX + 1);
-               readlink(sl, link_target, st.st_size);
+               link_target = g_malloc(st.st_size + 1);
+               i = readlink(sl, link_target, st.st_size);
+               if (i<0)
+                       {
+                       g_free(link_target);
+                       goto orig_copy;  // try a "normal" copy
+                       }
                link_target[st.st_size] = '\0';
 
                if (link_target[0] != G_DIR_SEPARATOR) // if it is a relative symlink
@@ -582,6 +588,7 @@ gboolean copy_file(const gchar *s, const gchar *t)
                                }
                        else                 // could not get absolute path, got some error instead
                                {
+                               g_free(link_target);
                                g_free(absolute);
                                goto orig_copy;  // so try a "normal" copy
                                }
```

**Comment by caclark** [comment] 2018-10-16 18:14
#640 is caused by this patch.
Although the reason is somewhere in Geeqie, the crash does not occur within Geeqie, so I cannot easily find the problem using the debugger.
The error shows the problem as a realloc or malloc problem.

**Comment by caclark** [comment] 2018-10-18 18:17
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=bedad2aeecc6c65ea36dc2ce44cc9d18dca1c605

Thanks to all...

**Closed by caclark** 2018-10-18 18:17 UTC
