### ISSUE TITLE
Geeqie needs a high-res icon

### ISSUE THREAD

**Issue by jose1711** [BestImageViewer/geeqie#811] opened 2020-09-20 05:33 UTC
`geeqie.png` with dimensions 48x48 looks heavily pixelated in Gnome, perhaps there's a similar issue with other desktop managers and I believe geeqie deserves at least 96x96 icon.

**Comment by tomaszg7** [comment] 2020-09-20 13:02
There is a even a vector version of the icon and it needs only to be installed: https://github.com/BestImageViewer/geeqie/issues/511

**Comment by caclark** [comment] 2020-09-20 14:31
Just executing:
`sudo cp <somewhere>/src/icons/svg/gqview_icon.svg /usr/share/pixmaps/geeqie.svg`

seems to be all that is necessary to install it. But my eyes don't detect any significant difference :-(

There are articles on the Internet about Gnome's new approach to icons that may be relevant. There have also been discussions here about a new (maybe simplified) icon for Geeqie.
If there were to be a change I would prefer that someone (other than me) would  create a uniform set of icons for Geeqie (most of the ones that I have incorporated have simply been a hack or straight copy from a licence-free icon from the Internet).

**Comment by jose1711** [comment] 2020-09-21 10:03
In addition to copying `svg` file into `/usr/share/pixmaps` I also had to rename/delete `geeqie.png`. Otherwise there was no effect.
Before:
![obrázok](https://user-images.githubusercontent.com/1406222/93754067-6b161e80-fc01-11ea-889b-bc93ca5deb69.png)
After:
![obrázok](https://user-images.githubusercontent.com/1406222/93754554-3b1b4b00-fc02-11ea-8206-48b4f8f26720.png)

**Comment by qarkai** [comment] 2024-08-25 11:01
@caclark Looks like duplicate of #179.

**Closed** 2024-08-27 11:27 UTC
