### ISSUE TITLE
Why doens't geeqie show WEBP thumbnails anymore?

### ISSUE THREAD

**Issue by Stalinist1** [BestImageViewer/geeqie#1183] opened 2023-09-02 19:54 UTC
It appears as it's broken image. But it's fine. I can easily open it in other applications.

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/72b639f3-6054-417d-a970-4bac642c09c2)

**Comment by caclark** [comment] 2023-09-03 08:42
Which OS and Geeqie version are you using?

**Comment by qarkai** [comment] 2023-09-03 11:03
@Stalinist1 
Could you provide this file for issue reproducing?

**Comment by caclark** [comment] 2023-09-03 11:10
@qarkai 
I think he may be using an AppImage. I see that the full-size AppImage does not display webp files, but the minimal version does.
I do not yet know why.

**Comment by Stalinist1** [comment] 2023-09-03 13:24
> Which OS and Geeqie version are you using?

Manjaro Linux, Geeqie 2.1 (latest in Manjaro repo)

**Comment by Stalinist1** [comment] 2023-09-03 13:27
> @Stalinist1 Could you provide this file for issue reproducing?

Any webp file!

For example, I just downloaded sample webp file from here
https://filesamples.com/samples/image/webp/sample1.webp

Here it is 
![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/cf857b75-af86-42df-b99d-cbe30b0a4fda)

**Comment by caclark** [comment] 2023-09-03 13:33
Could you please try:
`sudo apt-get install webp-pixbuf-loader`

**Comment by qarkai** [comment] 2023-09-03 13:36
> Could you please try: `sudo apt-get install webp-pixbuf-loader`

There is no apt-get on Manjaro. Use `sudo pacman -Syu webp-pixbuf-loader`.

**Comment by Stalinist1** [comment] 2023-09-03 13:48
Nothing happened

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/8c0d9a57-579e-418a-a78a-af91a0023eb6)

Geeeqie is restarted

![изображение](https://github.com/BestImageViewer/geeqie/assets/33825590/cdc08047-fec0-4bc0-9274-11101f161306)

**Comment by caclark** [comment] 2023-09-03 14:00
There is more discussion of webp in this issue #1076.

It is noted there that webp-pixbuf-loader 0.2.4 (which is the version you have) has a bug.
The last version I found to run was 0.2.1

The v2.1 AppImage shows webp images, if that may help.
https://github.com/BestImageViewer/geeqie/releases

**Comment by Stalinist1** [comment] 2023-09-03 17:33
Why did you break the Geeqie?
Before its update I could view `webp` files, and BTW no extra packages like `webp-pixbuf-loader` were installed?

**Comment by caclark** [comment] 2023-09-03 18:05
Geeqie depends on library files to handle the decoding of images of many image formats. If there is a bug in one of those library files, it is not really a Geeqie bug.

In some cases someone (sometimes me) has created a loader to handle an image format that is not yet provided by a library, This was the case for webp. When a library became available I removed the hand-made files and used the newly available library.
Unfortunately, in this case, the latest version of the library has a bug.

[Because of this, and another problem relating to webp, I will probably revert to the image loader I wrote. This does not help you.]

The v2.1 AppImage is generated from exactly the same source files as the Geeqie file you have installed. There is an .asc that you can use to verify the contents.

Other than that option, there is a Flatpak version (but I do not know its status), or you must wait for the next release of Geeqie which will be several months away

**Comment by Stalinist1** [comment] 2023-09-03 18:11
Ok, where can I find AppImage and how to install it?

**Comment by caclark** [comment] 2023-09-03 18:24
`wget https://github.com/BestImageViewer/geeqie/releases/download/v2.1/Geeqie-v2.1-x86_64.AppImage`
`chmod +x Geeqie-v2.1-x86_64.AppImage`
`./Geeqie-v2.1-x86_64.AppImage`

This file takes a while to load because of its size. 

If you are only doing basic viewing of images. this AppImage loads faster:
`wget https://github.com/BestImageViewer/geeqie/releases/download/continuous/Geeqie-minimal-latest-x86_64.AppImage`

**Comment by caclark** [comment] 2023-09-04 09:58
Fixed in commit 4b159311f17c66

**Closed by caclark** 2023-09-04 09:58 UTC

**Comment by Stalinist1** [comment] 2023-11-13 08:11
Today I installed new version and now I can see WEBP images.
Thanks to developers.
