### ISSUE TITLE
Directory widget loses focus on tab completion

### ISSUE THREAD

**Issue by LdBarthel** [BestImageViewer/geeqie#592] opened 2018-02-21 14:10 UTC
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
"Geeqie 1.4"
gtk3 3.22.26+161+g60750b3ffd-1

### OS / DISTRIBUTION
Arch Linux
last full update 2018-02-06
geeqie-1.4-1 package is current

### SUMMARY
While navigating a directory hierarchy using tab completion, the widget loses focus and requires another mouse click to regain focus. Worse, because geeqie has so many single letter commands without modifier keys,  the characters typed after focus is lost frequently result in unexpected changes that have to be backed out.

Expected behavior is that the widget should retain focus until the user clicks elsewhere in the window. 

### STEPS TO REPRODUCE
Choose a directory hierarchy to navigate. (/usr/share/icons/hicolor should be a good example)
Click to focus the text widget, then begin typing.
If you can type the entire path from memory, the text widget retains focus until you hit [Enter].
If you hit [TAB] to complete the subdirectory name, focus will jump to the first image in that subdirectory. (If there are no images, focus apparently goes to the main window.)
It is impossible to quickly navigate using "/usr/share/icons/hic[TAB]16[TAB]app[TAB]" without reaching for the mouse after every [TAB].

Even if the cursor keys are used to choose from potential completions, focus should remain with the text widget.

**Comment by caclark** [comment] 2018-03-03 19:12
The problem seems to be caused by a call to layout_set_path(), which is shifting the focus.
Attached is a .diff file which simply eliminates a piece of code.
It works at a trivial level, but there are some parts I don't understand. At the moment this is on the list of things for me to do, maybe.
Unless someone else wants to take a look.
[592-1.diff.gz](https://github.com/BestImageViewer/geeqie/files/1777794/592-1.diff.gz)

**Comment by caclark** [comment] 2018-03-04 12:01
Fixed in commit dfa9b96 at geeqie.org

**Closed by caclark** 2018-03-04 12:01 UTC
