### ISSUE TITLE
Mailing lists - a bad habit

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#440] opened 2016-10-31 17:34 UTC
> You are not allowed to post to this mailing list, and your message has
been automatically rejected.  If you think that your messages are
being rejected in error, contact the mailing list owner at
geeqie-devel-owner@lists.sourceforge.net.

Consider switching to GitHub. Really switching, not just having a sort of delayed echo here. GitHub is friendly, powerful yet easy to use, it encourages people to connect, it does not have that spam scent about it which signing up to a mailing list incurs, and, unlike mailing lists, it does not tell me I'm "not allowed" to write something and force me to email more people to get around that, by which point my time has been wasted and I've become completely put off at the prospect of helping out.

I updated Geeqie's website and I'd be happy to help out with it again, but if you'd like a hand with that then contact me via GitHub - I'm unsubscribing from the mailing list.

> Subject	Re: [Geeqie-devel] GTK+3
Hello
Word of advice: work with Gtk+ 3.22.
Reasons:
1. A theme made for Gtk+ <=3.18 will likely not work at all with >=3.20. Such was my experience.
2. Gtk+ 3.22 is meant to be the last 3.x release, and is said to be "as rock-stable (and hence "boring") as GTK+ 2".
3. As time passes, more and more distros will ship 3.22, with all older versions being phased out.
4. By developing for 3.22 right away you will save yourself the headache of having to deal with <=3.20 bugs and oddities and of having to re-develop things to get them working with that version.
Gtk Inspector is your friend https://wiki.gnome.org/Projects/GTK%2B/Inspector
Kind regards

**Comment by gdt** [comment] 2016-10-31 22:54
I object to giving up on the mailinglist.   @Beep6581 is incorrect when asserting that github comments have no barrier while mailinglists require signing up.   People without github accounts cannot comment.    Mailinglists have a real community of people who are long-term interested, and I've been seeing drive-by issue filers in lots of projects.  I'm not suggesting getting rid of the issue tracker - just that "use github" is not a panacea and is not a reasonable approach to many people who have been involved in free software for a long time.

In addition, calling mailing lists a bad habit is presumptuous and rude.  It's obvious that some people prefer them, and some people prefer github.

**Comment by xsdg** [comment] 2016-12-29 21:41
For some historical context: The Geeqie project has been burned before by overzealous switching to a new platform.  It started on SourceForge back when SF was still the de-facto hosting platofmr for open-source projects.  Over time, SF became increasingly commercialized, with no real benefit for us.  Among other things, it didn't add git support for the longest time.  Generally speaking, commercial entities tend to have long-term goals that align with their customers, but may have short-term goals that antagonize their customers.

In an attempt to avoid the commercialization trap, we switched our code repository to Gitorious.  And then Gitorious was shut down.  So now we're dual-homed between the geeqie.org repository (run by @mowgli himself) and GitHub.  git's inherent decentralization makes it convenient to switch, which is a nice property.

Switching communication platforms is difficult, though.  The mailing list is a known quantity.  It's not perfect, but we're aware of the quirks, and they seem reasonable to live with.  Everyone has an email account, and it's trivial to join and depart the list.  Beyond that, list archives that don't live on the site itself have been common for a long, long time — if sourceforge.net were to disappear one day, the archives would survive via sites like GMane.

Were we to attempt to jump over to GitHub, it would mean abandoning the list archives, and hoping that GitHub sticks around for the long haul — if GitHub disappeared, it seems like all of the messages that lived here would disappear as well.  It would also mean abandoning the people who are already part of the Geeqie dev community and, for whatever reason, don't want to use GitHub.  Currently, those people can still contribute — they can send patches to the list, and/or push patches directly to the geeqie.org repository if they have that access.

**Comment by Beep6581** [comment] 2016-12-29 22:35
@xsdg good arguments, and I have been part of migrating a project through several issue tracking/source code management services before so I know what that entails. However git and GitHub are separate things so I see no problem at all with the source code management side of things. That leaves you with the issue discussion log. Google Code made exporting that easy. GitHub has several options of exporting a whole project, for example [this](https://github.com/joeyh/github-backup) and [this](https://api.github.com/repos/BestImageViewer/geeqie/issues), so losing conversations is not a problem either. Further, one can comment on issues using email, so those who are resistant to change can keep sending emails. Having a GitHub account removes all obstacles from interacting with thousands of other projects, and it also allows easy login to non-GitHub services. It also never out of whim prevents me from submitting a long report I just typed, as the Geeqie mailing list did.

**Comment by mowgli** [comment] 2020-12-02 19:40
@xsdg described it very good.

Lets add that recently, Github was sold to Microsoft what makes it not so clear what way Github will go to make profit. Even the simplicity of Github got already droped as now you need javascript to see more stuff as needed before. And one get nerfed with popups an "yes I know" windows.

The access to Geeqie should have its place on a fix location, on geeqie.org. With the record of lost developers caused by the many moves, I oppose the full move to Github. The small developer support we have is very fragile. 'Won't risk that.

So I close this issue with wontfix.

**Closed by mowgli** 2020-12-02 19:40 UTC
