### ISSUE TITLE
Running 'make check' in po folder errors out

### ISSUE THREAD

**Issue by gusnan** [BestImageViewer/geeqie#781] opened 2020-07-19 15:59 UTC
### ISSUE TYPE
* Bug Report

### GEEQIE VERSION
```
Latest Git from geeqie.org
```

```
GTK 3
```

### OS / DISTRIBUTION
Debian stable and unstable

### SUMMARY
Doing 'make check' in the po folder gives this:
```
gusnan@debian-i7:~/kod/git/geeqie/geeqie/po [master:u]> LC_ALL=C make check
rm -f missing notexist
srcdir=. /usr/bin/intltool-update -m
Unmatched ( in regex; marked by <-- HERE in m/^geeqie-m4_esyscmd_s( <-- HERE gitrev-parse--quiet--verify--shortHEAD/.*$/ at /usr/bin/intltool-update line 320, <FILE> line 139.
make: *** [Makefile:280: check] Error 25
```

Using the Debian packaged intltool on both stable and unstable (it's the same version on both Debian versions): intltool-update (intltool) 0.51.0

### STEPS TO REPRODUCE
Run make check in the po folder.

**Comment by caclark** [comment] 2020-07-22 11:56
This seems to be caused by the line:
`AC_INIT([geeqie], m4_esyscmd_s(git rev-parse --quiet --verify --short HEAD), [geeqie@freelists.org], [], [http://www.geeqie.org/])`
in file configure.ac.

It seems to me that when "make" is run, the m4_ command generates a version number.
When "make check" is run the m4_ string is used as the version number.

I have no understanding of the generation process, so I will leave this to someone else to solve.

**Comment by gusnan** [comment] 2020-07-22 12:26
Ah, of course. It might very well be that it works just fine when running it in the geeqie repository, but I run into this when I am packaging a git snapshot for Debian, where I export the geeqie git to a tar, and import in a Debian packaging git repository.

**Comment by gusnan** [comment] 2020-07-22 13:51
Closing this bug, it is caused by my own user error.

**Comment by gusnan** [comment] 2020-08-06 13:56
Reopening this - I run into this also on a clean git checkout of the repo on geeqie.org - commit 30b97e86.

**Comment by caclark** [comment] 2020-08-06 16:07
I continue to know absolutely nothing about this :-(
But I note that any commit that has a release tag is ok, and all other commits are not ok.

**Comment by gusnan** [comment] 2020-08-06 18:15
I might have some information regarding this - First problem is that the git command includes a newline, which confuses the process - this is fixable by changing the AC_INIT command to

`
AC_INIT([geeqie], m4_esyscmd([git describe --abbrev=7 --dirty --always --tags | tr -d '\n']), [geeqie@freelists.org], [], [http://www.geeqie.org/])
`

(however, see https://stackoverflow.com/questions/43526939/how-to-insert-git-based-version-in-autoconf-managed-project for comments on this method).

And then, if I run this on the master branch, will give a version like v1.2-800-g909ac473 , which is the result since the tags are on separate branches in the geeqie.org repository for each release, like "stable/1.3" and "stable/1.5", and not on the master branch - the 1.2 is the last one on the master branch.

**Comment by caclark** [comment] 2020-08-07 10:47
If it is just a matter of removing a newline, would this work?:
`AC_INIT([geeqie], m4_esyscmd([git rev-parse --quiet --verify --short HEAD | tr -d '\n']), [geeqie@freelists.org], [], [http://www.geeqie.org/])`

**Comment by gusnan** [comment] 2020-08-07 13:32
It works to build, but please notice that this is also the version number that is shown in the cli option --version, and also in the about dialog. It might be an idea to show something like 1.5.1+git[commit_id] there.

**Comment by caclark** [comment] 2020-08-07 16:04
Do you mean something like the following?
There are obviously assumptions made about the format of the tags.

`AC_INIT([geeqie], m4_translit(m4_esyscmd([git tag -l v[1-9]* | tail -n1 | tr -d 'v' && echo "+git" && git rev-parse --quiet --verify --short HEAD]), m4_newline), [geeqie@freelists.org], [], [http://www.geeqie.org/])`

**Comment by gusnan** [comment] 2020-08-07 16:16
Nice! I believe that would work fine. One minor thought I have is it could be nice for people who package git snapshots, to include the date before the git hash, so that they would sort in proper order. (I have used dates when packaging git snapshots in Debian). This makes the version number a bit long though.

**Comment by caclark** [comment] 2020-08-08 09:23
Maybe like so:?

`AC_INIT([geeqie], m4_translit(m4_esyscmd([git tag -l v[1-9]* | tail -n1 | tr -d 'v' && echo "+git" && git log -1 --date=format:"%Y%m%d" --format="%ad" && echo "-" && git rev-parse --quiet --verify --short HEAD]), m4_newline), [geeqie@freelists.org], [], [http://www.geeqie.org/])`

**Comment by gusnan** [comment] 2020-08-08 12:22
Look great to me. Thanks for your work with this!

**Comment by caclark** [comment] 2020-08-08 13:24
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=d43baf2c1b499a05cebc171550f3891d0cf53537

**Closed by caclark** 2020-08-08 13:24 UTC

**Comment by caclark** [comment] 2020-11-11 15:39
Running this revised command  on a new release tagged as e.g. v1.6, will result in the version number being displayed with the full string of version-date-commit.
Is it necessary to filter out date and/or commit when the tag and the latest commit are the same?

**Comment by gusnan** [comment] 2020-11-11 16:36
Nah, I don't mind having it. It could be nice to separate a snapshot from a proper release, but I don't mind either way.

**Comment by caclark** [comment] 2020-11-12 12:39
If the tag is at HEAD show the version number only, otherwise show version-date-commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=fae4de3c647dc77b6a91830de2e3d989d4c70824
