### ISSUE TITLE
GTK3 problem with Select Color Profile window

### ISSUE THREAD

**Issue by Beep6581** [BestImageViewer/geeqie#442] opened 2016-12-19 20:59 UTC
Commit 3ad88b1
https://i.imgur.com/uht6MFy.png
GTK+ 3.22.3
gtkmm 3.20.1

**Comment by caclark** [comment] 2017-05-02 09:14
Fixed in commit b8995ea at geeqie.org

**Comment by Beep6581** [comment] 2017-05-02 14:01
The problem is not fixed.

Commit b8995ea4
![imgur-2017_05_02-16 00 31](https://cloud.githubusercontent.com/assets/5844619/25621071/8f4fe276-2f50-11e7-8941-6fed358c390c.png)
![imgur-2017_05_02-16 00 46](https://cloud.githubusercontent.com/assets/5844619/25621070/8f0ceae8-2f50-11e7-9dd2-49c597c72447.png)

**Comment by caclark** [comment] 2017-05-02 15:53
I'm sorry, but I don't understand where the problem is. Is it that you see .icm as well as .icc?

**Comment by Beep6581** [comment] 2017-05-02 15:58
No, I expect to see both ICM and ICC. It's the huge gap between "Select color profile" and the rest of the contents.

**Comment by Beep6581** [comment] 2017-05-03 10:43
This issue should not be closed as it's not fixed.

**Comment by caclark** [comment] 2017-05-03 17:58
OK, I see now. I had assumed that your original report referred to the functional problem that existed in all dialogues that use the path filter combo-box. That was the problem I fixed.
The visual problem you now point out is something else. Actually, if you re-size any dialogue you will see that effect.
The issue is now reopened.

**Comment by Beep6581** [comment] 2017-05-03 18:09
@caclark I will be more explicit in my future posts :)

**Closed** 2017-05-20 07:18 UTC
