### ISSUE TITLE
geeqie core dumps (for me) on symlink copy

### ISSUE THREAD

**Issue by pittendrigh** [BestImageViewer/geeqie#640] opened 2018-10-10 17:55 UTC
geeqie 1.4 on Mint Linux Tara.

If I copy a  -type f image from here to there everything is fine.

But if I try to copy a symlink from here to there geeqie core dumps. Every time.

**Comment by caclark** [comment] 2018-10-16 18:11
Fixed in commit:
http://geeqie.org/cgi-bin/gitweb.cgi?p=geeqie.git;a=commit;h=7562336c2d025dfc85e3795034594711379bc0ed

The fault is caused by the additions of #544.

**Closed by caclark** 2018-10-16 18:11 UTC
Labels: bug
